INSERT INTO node (
    node_id,
    node_child_id,
    node_con_desc,
    node_con_name,
    node_contextual_expected_duration,
    node_is_expanded,
    node_is_locked,
    node_parent_id_fk,
    node_project_id,
    node_return_state,
    node_return_value,
    node_test_return_state,
    node_test_return_value,
    node_urn,
    node_x,
    node_y)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (node_id) DO UPDATE SET
                                    node_child_id = excluded.node_child_id,
                                    node_con_desc = excluded.node_con_desc,
                                    node_con_name = excluded.node_con_name,
                                    node_contextual_expected_duration = excluded.node_contextual_expected_duration,
                                    node_is_expanded = excluded.node_is_expanded,
                                    node_is_locked = excluded.node_is_locked,
                                    node_parent_id_fk = excluded.node_parent_id_fk,
                                    node_project_id = excluded.node_project_id,
                                    node_return_state = excluded.node_return_state,
                                    node_return_value = excluded.node_return_value,
                                    node_test_return_state = excluded.node_test_return_state,
                                    node_test_return_value = excluded.node_test_return_value,
                                    node_urn = excluded.node_urn,
                                    node_x = excluded.node_x,
                                    node_y = excluded.node_y